$lines = Get-Content "lib/screens/home_screen.dart"
$before = $lines[0..978]
$newBlock = @(
"          Divider(color: Colors.white12, height: 1),",
"          const SizedBox(height: 8),",
"          Padding(",
"            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),",
"            child: GestureDetector(",
"              onTap: () {",
"                Navigator.pop(context);",
"                if (isParent) {",
"                  context.read<PinProvider>().enterChildMode();",
"                } else {",
"                  Navigator.push(context, MaterialPageRoute(",
"                    builder: (_) => const PinVerificationScreen()));",
"                }",
"              },",
"              child: Container(",
"                padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),",
"                decoration: BoxDecoration(",
"                  gradient: LinearGradient(colors: [",
"                    isParent ? Colors.redAccent.withOpacity(0.2) : Colors.greenAccent.withOpacity(0.2),",
"                    Colors.transparent,",
"                  ]),",
"                  borderRadius: BorderRadius.circular(14),",
"                  border: Border.all(",
"                    color: isParent ? Colors.redAccent.withOpacity(0.5) : Colors.greenAccent.withOpacity(0.5),",
"                  ),",
"                ),",
"                child: Row(",
"                  children: [",
"                    Icon(",
"                      isParent ? Icons.child_care_rounded : Icons.admin_panel_settings_rounded,",
"                      color: isParent ? Colors.redAccent : Colors.greenAccent,",
"                      size: 22,",
"                    ),",
"                    const SizedBox(width: 12),",
"                    Text(",
"                      isParent ? 'Passer en mode Enfant' : 'Passer en mode Parent',",
"                      style: TextStyle(",
"                        color: isParent ? Colors.redAccent : Colors.greenAccent,",
"                        fontWeight: FontWeight.bold,",
"                        fontSize: 14,",
"                      ),",
"                    ),",
"                    const Spacer(),",
"                    Icon(",
"                      Icons.swap_horiz_rounded,",
"                      color: isParent ? Colors.redAccent : Colors.greenAccent,",
"                      size: 18,",
"                    ),",
"                  ],",
"                ),",
"              ),",
"            ),",
"          ),"
)
$after = $lines[979..($lines.Count-1)]
$result = $before + $newBlock + $after
Set-Content "lib/screens/home_screen.dart" -Value $result -Encoding UTF8
Write-Host "DONE: $((Get-Content 'lib/screens/home_screen.dart' | Measure-Object -Line).Lines) lignes" -ForegroundColor Green
