name: Deploy Firebase Functions

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'functions/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: cd functions && npm install

      - name: Create service account file
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > sa.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create firebase.json
        run: |
          echo '{
            "functions": {
              "source": "functions",
              "runtime": "nodejs20"
            }
          }' > firebase.json

      - name: Create .firebaserc
        run: |
          echo '{
            "projects": {
              "default": "sks-familly-3f205"
            }
          }' > .firebaserc

      - name: Deploy Functions
        run: firebase deploy --only functions --project sks-familly-3f205 --force
        env:
          GOOGLE_APPLICATION_CREDENTIALS: sa.json
